-- MySQL Script generated by MySQL Workbench
-- ter 29 set 2026 08:42:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_rede_social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_rede_social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_rede_social` ;
USE `banco_rede_social` ;

-- -----------------------------------------------------
-- Table `banco_rede_social`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_rede_social`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rede_social`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_rede_social`.`postagem` (
  `idpostagem` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(140) NOT NULL,
  `data_hora` TIMESTAMP NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idpostagem`),
  INDEX `fk_postagem_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `banco_rede_social`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rede_social`.`curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_rede_social`.`curtida` (
  `idusuario` INT NOT NULL,
  `idpostagem` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `idpostagem`),
  INDEX `fk_usuario_has_postagem_postagem1_idx` (`idpostagem` ASC) VISIBLE,
  INDEX `fk_usuario_has_postagem_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_postagem_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `banco_rede_social`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_postagem_postagem1`
    FOREIGN KEY (`idpostagem`)
    REFERENCES `banco_rede_social`.`postagem` (`idpostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rede_social`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_rede_social`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpostagem` INT NOT NULL,
  `texto` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_usuario_has_postagem_postagem2_idx` (`idpostagem` ASC) VISIBLE,
  INDEX `fk_usuario_has_postagem_usuario2_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_postagem_usuario2`
    FOREIGN KEY (`idusuario`)
    REFERENCES `banco_rede_social`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_postagem_postagem2`
    FOREIGN KEY (`idpostagem`)
    REFERENCES `banco_rede_social`.`postagem` (`idpostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_rede_social`.`seguir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_rede_social`.`seguir` (
  `idseguidor` INT NOT NULL,
  `idseguindo` INT NOT NULL,
  PRIMARY KEY (`idseguidor`, `idseguindo`),
  INDEX `fk_usuario_has_usuario_usuario2_idx` (`idseguindo` ASC) VISIBLE,
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`idseguidor` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`idseguidor`)
    REFERENCES `banco_rede_social`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario2`
    FOREIGN KEY (`idseguindo`)
    REFERENCES `banco_rede_social`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
