-- MySQL Script generated by MySQL Workbench
-- ter 01 set 2026 10:39:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_escola` ;
USE `banco_escola` ;

-- -----------------------------------------------------
-- Table `banco_escola`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `area` VARCHAR(60) NOT NULL,
  `carga_horaria` INT NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_escola`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `data_nascimento` DATE NULL,
  `formacao` VARCHAR(100) NULL,
  PRIMARY KEY (`idprofessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_escola`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `idcurso` INT NOT NULL,
  `nome` VARCHAR(60) NULL,
  `idprofessor` INT NOT NULL,
  PRIMARY KEY (`idturma`),
  INDEX `fk_turma_curso_idx` (`idcurso` ASC) VISIBLE,
  INDEX `fk_turma_professor1_idx` (`idprofessor` ASC) VISIBLE,
  CONSTRAINT `fk_turma_curso`
    FOREIGN KEY (`idcurso`)
    REFERENCES `banco_escola`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`idprofessor`)
    REFERENCES `banco_escola`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_escola`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_escola`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(240) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(240) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
